name: Action sistema bancário

on:
  push:
    branches: [ develop, feature/release_workflow ]
  pull_request:
    branches: [ develop, feature/release_workflow ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Resolve project dependencies
        run: ./gradlew --refresh-dependencies

      - name: Compile
        run:  ./gradlew bootJar

      - name: Run unit tests
        run: ./gradlew test

      - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

