name: release workflow

on:
  push:
    branches: [ release, develop ]
  pull_request:
    branches: [ release, develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Resolve project dependencies
        run: ./gradlew --refresh-dependencies

      - name: Compile
        run:  ./gradlew bootJar

      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '6.40.0'
          analyzeModifiedFilesOnly: false
          rulesets: 'rulesets/default.xml'
      - name: Check PMD violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1

      - name: Run unit tests
        run: ./gradlew test

      - uses: actions/upload-artifact@v3
        with:
          name: latest-build
          path: build/libs/DIM0517_sistema_bancario-1.0-SNAPSHOT.jar
